spring:
  application:
  name: authentication-service

  spring:
    kafka:
      bootstrap-servers: localhost:9092
      producer:
        key-serializer: org.apache.kafka.common.serialization.StringSerializer
        value-serializer: org.apache.kafka.common.serialization.StringSerializer
    data:
      redis:
        host: localhost
        port: 6379
        timeout: 2000
auth:
  cookie:
    name: sid
    domain: localhost
    secure: true
    http-only: true
    same-site: Lax
    max-age-seconds: 1209600 # 14 ????
  keycloak:
    base-url: http://localhost:9090
    realm: chat
    client-id: chatclient
    client-secret: vx2C1sgWJnd17ywYMUTVUx2kvsztB2TJ   # ?????? ??? ????????????????? ???????
    admin:
      realm: master
      client-id: admin-cli
      username: admin
      password: admin
  tokens:
    access-ttl-seconds: 300
    refresh-ttl-seconds: 1209600 # 14 ????
kafka:
  topics:
    user-created: user.created
server:
  port: 8080
